services:
  wireadmin:
    environment:
      # ⚠️ Required:
      # Make sure change this to your host's public address
      - WG_HOST=localhost
      # ⚠️ Required:
      # You can use `openssl rand -base64 8` to generate a secure password
      - ADMIN_PASSWORD=super-secret-password

    image: ghcr.io/wireadmin/wireadmin
    container_name: wireadmin
    restart: unless-stopped
    volumes:
      - wireadmin-data:/data
      - tor-data:/var/lib/tor
    ports:
      - '3000:3000/tcp'
      # Dnsmasq
      #- '53:53/udp'
      #- '53:53/tcp'
      # WireGuard
      - '51820:51820/udp'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  wireadmin-data:
  tor-data:
